In [ ]:
#1 (a)
import numpy as np
arr=[1,2,3,6,4,5]
print(arr)
print("Reversed arr :",np.flip(arr))

[1, 2, 3, 6, 4, 5]
Reversed arr : [5 4 6 3 2 1]


In [ ]:
#1 (b)
array1=np.array([[1,2,3],[2,4,5],[1,2,3]])
print("Flattened arr :",array1.flatten())
print("Flattened by F :",array1.flatten('F'))
print("Flattened :",array1.flatten('C'))

Flattened arr : [1 2 3 2 4 5 1 2 3]
Flattened by F : [1 2 1 2 4 2 3 5 3]
Flattened : [1 2 3 2 4 5 1 2 3]


In [ ]:
#1 (c)
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
comp=(arr1==arr2)
print(comp)

[[ True  True]
 [ True  True]]


In [ ]:
#1 (c)
arr1=[1,2,3,4]
arr2=[1,2,3,4]
comp=(arr1==arr2)
print(comp)

True


In [ ]:
#1 (d)
x=np.array([1,2,3,4,5,1,2,1,1,1])

def most_frequent_and_indices(x):
    unique_elements, counts = np.unique(x, return_counts=True)
    max_count_index = np.argmax(counts)
    most_frequent_element = unique_elements[max_count_index]
    return most_frequent_element, np.where(x == most_frequent_element)[0]
result = most_frequent_and_indices(x)
print(result)

(1, array([0, 5, 7, 8, 9]))


In [ ]:
#1 (e)
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
print("Sum :",np.sum(gfg))
print("Col sum :",np.sum(gfg, axis=0))
print("Row sum :",np.sum(gfg, axis=1))

Sum : 45
Col sum : [[20  9 16]]
Row sum : [[14]
 [16]
 [15]]


In [ ]:
#1 (f)
n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])
print("Diag sum :",np.trace(n_array))
print(np.linalg.eig(n_array))
print("Inverse :",np.linalg.inv(n_array))
print("Determinant :",np.linalg.det(n_array))

Diag sum : 176
EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
Inverse : [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant : 137180.0000000001


In [ ]:
#1 (g)
p=np.array([[1,2],[2,3]])
q=np.array([[4,5],[6,7]])
print("Multiplication :",np.dot(p,q))
print("Covariance :",np.cov(p,q))

Multiplication : [[16 19]
 [26 31]]
Covariance : [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
#1 (g)
p=np.array([[1,2],[2,3],[4,5]])
q=np.array([[4,5,1],[6,7,2]])
print("Multiplication :",np.dot(p,q))

Multiplication : [[16 19  5]
 [26 31  8]
 [46 55 14]]


In [ ]:
#1 (h)
x=np.array([[2,3,4],[3,2,9]])
y=np.array([[1,5,0],[5,10,3]])
print("Inner :",np.inner(x,y))
print("Outer :",np.outer(x,y))
print("Cross :",np.cross(x,y))

Inner : [[17 52]
 [13 62]]
Outer : [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cross : [[-20   4   7]
 [-84  36  20]]


In [ ]:
#2 (a)
import numpy as np
array=np.array([[1,-2,3],[-4,5,-6]])
print("Absolute :",np.abs(array))
x=array.flatten()
print("25th percentile :",np.percentile(x,[25],axis=0))
print("50th percentile :",np.percentile(x,[50],axis=0))
print("75th percentile :",np.percentile(x,[75],axis=0))

print("Mean :",np.mean(array))
print("Median :",np.median(array))
print("Standard deviation :",np.std(array))
# It appears that you are trying to calculate the 50th percentile along axis=1 of
# a flattened array x. However, flattening an array using .flatten() returns a
# 1-dimensional array. In 1-dimensional arrays, there is only axis=0.

Absolute : [[1 2 3]
 [4 5 6]]
25th percentile : [-3.5]
50th percentile : [-0.5]
75th percentile : [2.5]
Mean : -0.5
Median : -0.5
Standard deviation : 3.8622100754188224


In [ ]:
#2 (b)
a=np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])
print("Floor :",np.floor(a))
print("Ceil :",np.ceil(a))
print("Trunc :",np.trunc(a))
print("Round :",np.round(a))

Floor : [-2. -2. -1.  0.  1.  1.  3.]
Ceil : [-1. -1. -0.  1.  2.  2.  3.]
Trunc : [-1. -1. -0.  0.  1.  1.  3.]
Round : [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
#3 (a)
import numpy as np
array=np.array([10,52,62,16,16,54,453])
print("Sorted array :",np.sort(array))
print("Indices :",np.argsort(array))
print("Elements :",sorted(array)[:4])
import heapq
print("Largest 5 elements :",heapq.nlargest(5,array))

Sorted array : [ 10  16  16  52  54  62 453]
Indices : [0 3 4 1 5 2 6]
Elements : [10, 16, 16, 52]
Largest 5 elements : [453, 62, 54, 52, 16]


In [ ]:
#3 (b)
array=np.array([1,1.2,2.2,2,3,2])
print("Integer elements :",array[array.astype(int)==array])
print("Float elements :",array[array.astype(float)==array])


Integer elements : [1. 2. 3. 2.]
Float elements : [1.  1.2 2.2 2.  3.  2. ]


In [1]:
#4
from PIL import Image
import numpy as np

def img_to_array(path):
  img = Image.open(path)
  if img.mode == 'RGB':
    arr = np.array(img)
    with open('rgb_image_array.txt', 'w') as f:
      for row in arr:
        np.savetxt(f, row, fmt='%d')
  elif img.mode == 'L':
    arr = np.array(img)
    with open('grayscale_image_array.txt', 'w') as f:
      np.savetxt(f, arr, fmt='%d')
  else:
    print("Unsupported image mode.")